### ISSUE TITLE
More frequent updates to offset file?

### ISSUE THREAD

**Issue by CMDR-Cometborne** [CMDR-Kiel42/EDMC_SpanshRouter#12]
The plugin stores the current position in the route in the offset file.  However, this is only done on a clean exit, and there are at least two cases where this mechanism fails:

1. EDMC sometimes silently crashes.  EDMC issue https://github.com/Marginal/EDMarketConnector/issues/439 was opened for this, and this is also being mentioned in the EDMC channel on the EDCD discord.
2. Tonight's Windows update also caused EDMC to exit in a way that did not trigger an update of the offset file.

If any of these happen while you are at waypoint 490 of 1088, it is quite annoying to click the next waypoint button until you are at right position again, especially as there is no auto-repeat. 

The alternative of closing EDMC, opening the plugin directory, loading route.csv in Calc, searching for the current system, manually updating offset with the line number, and restarting EDMC is easier on the mouse button, but also takes time.

Can you update the offset file more often, please?  Preferably, it should be updated each time you advance to another waypoint, but even an update every 5-10 jumps would already been a huge improvement.

**Comment by CMDR-Kiel42** [comment]
Saving the offset at each waypoint is doable, I'll add it in the next update. Sorry you had to go through all that.

**Comment by CMDR-Kiel42** [comment]
Fixed in release 2.1.4.
