### ISSUE TITLE
Fails to load a file with 679 body entries in a R2R CSV

### ISSUE THREAD

**Issue by lilmnm-kamikaze-** [CMDR-Kiel42/EDMC_SpanshRouter#18]
Hello I have a CSV file from Road to riches file from Brani to Colonia with a max system set to 1000. when i try to load this into the plugin it fails. I have another csv with a max of 250 systems  and it loads just fine to the same point.

For now i have split my large file to smaller 200 system routes and it loads fine. If there is a max file size or something but i get the error "An error occurred while reading the file." when i try to load the file as a whole

**Comment by CMDR-Kiel42** [comment]
Hi! It's odd, I haven't set a maximum. 
Could you send me the file? (Just attach it to a new comment)
That way I can take a closer look at what's wrong.

**Comment by lilmnm-kamikaze-** [comment]
yeah sure i forgot to add them last night. sorry. 
I will add both files i was using.
[riches-Brani-Colonia-250 sytems.csv.txt](https://github.com/CMDR-Kiel42/EDMC_SpanshRouter/files/4430149/riches-Brani-Colonia-250.sytems.csv.txt)
[riches-Brani-Colonia-1000.csv.txt](https://github.com/CMDR-Kiel42/EDMC_SpanshRouter/files/4430150/riches-Brani-Colonia-1000.csv.txt)

**Comment by lilmnm-kamikaze-** [comment]
After doing some additional tests i found that the issue is from the file itself. 
I used exel before getting this plugin to keep track of where i left off and to copy the system. then when i got this i saved a copy of that file as csv from the xlsx format that exel uses.

I am still unsure why it fails to load the csv file if its saved from exel.

**Comment by CMDR-Kiel42** [comment]
I've checked it out, Excel adds some Unicode info at the beginning of the file. It's is invisible in an editor, but the programs picks up on it and doesn't recognize the header as valid.
I'll write a fix.
In the meantime, in Excel, you can try to go to the Tools->"Web options" menu (in the save as dialog) set the encoding to UTF8 (not UTF8-BOM). I am not sure if it works as I do not use Excel at work, but I'll be able to confirm on monday if it's a viable workaround.

**Comment by lilmnm-kamikaze-** [comment]
all i did was opened the CSV file in notepad++ and then saved the split parts in new files and kept the original as it was. That's why the split files worked but not the original.

**Comment by CMDR-Kiel42** [comment]
Fixed in release 3.0.0
