### ISSUE TITLE
Python error upon EDMC startup

### ISSUE THREAD

**Issue by CMDR-Cometborne** [CMDR-Kiel42/EDMC_SpanshRouter#20]
From %temp%/EDMarketConnector.log on Windows 10, EDMC 3.46, plugin version 3.0.2

loading plugin SpanshRouter from "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\SpanshRouter\load.py"
No previously saved route.
!! Traceback (most recent call last):
!!   File "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\SpanshRouter\SpanshRouter\SpanshRouter.py", line 276, in open_last_route
!!   File "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\SpanshRouter\SpanshRouter\SpanshRouter.py", line 288, in copy_waypoint
!! AttributeError: 'NoneType' object has no attribute 'clipboard_clear'

The message "no previously saved route" is strange because there is a route and it is displayed in the UI, and things are working properly.

**Comment by CMDR-Kiel42** [comment]
That's odd, from the logs it looks like the "copy to clipboard" feature doesn't work anymore. Are the waypoints properly copied to your clipboard when you run the plugin?

**Comment by CMDR-Kiel42** [comment]
Fixed in [this commit](https://github.com/CMDR-Kiel42/EDMC_SpanshRouter/commit/2c5a4b11d5da1c37270d4216dc6ea8ff1bec59da). This will be added to the next release.

**Comment by CMDR-Cometborne** [comment]
Yes, the clipboard is still working.  Thank you for the quick fix.

**Comment by CMDR-Kiel42** [comment]
Fixed in [release 3.0.3](https://github.com/CMDR-Kiel42/EDMC_SpanshRouter/releases/tag/v3.0.3)
