### ISSUE TITLE
Suggestions appear after route is plotted

### ISSUE THREAD

**Issue by RapidfireCRH** [CMDR-Kiel42/EDMC_SpanshRouter#21]
When entering systems in for source and destination, the suggestions are not cleared when a route is plotted.

Steps to reproduce:
1. enter a system in source or destination but do not select suggestion dropdown
2. plot route
3. suggestion stays even though route is already plotted

This is the 3.0.4 release and EDMC version 4.0.2.0

**Comment by RapidfireCRH** [comment]
![image](https://user-images.githubusercontent.com/30603500/87592832-c084fb00-c6a7-11ea-82e4-8585702fec06.png)

**Comment by CMDR-Kiel42** [comment]
Fixed in [this commit](https://github.com/CMDR-Kiel42/EDMC_SpanshRouter/commit/face54fc95189823f5825e0525e442ba62ad3215). This will be included in the next release.
