### ISSUE TITLE
create routes for Fleet Carriers

### ISSUE THREAD

**Issue by batkung** [CMDR-Kiel42/EDMC_SpanshRouter#22]
would it be possible to modify this plugin to add routes that don't use neutrons so that they can be used for fleet carriers? possibly a FC checkbox that will just generate a standard route of max jump distance 500LY per hop.

**Comment by CMDR-Kiel42** [comment]
Hi, the route plotting is done by [Spansh](https://www.spansh.co.uk/plotter). They have a [Fleet Carrier Router](https://www.spansh.co.uk/fleet-carrier) there, which allows you to export the route to CSV. You can then import this file in the plugin. I just tested it, unfortunately there seems to be a bug when saving the route in the plugin, but apart from that it seems functional.

I do intend to implement the FC router further down the line.
