### ISSUE TITLE
Imported CSV case sensitive

### ISSUE THREAD

**Issue by rdc000** [CMDR-Kiel42/EDMC_SpanshRouter#23]
I use a particular source of system name lists which outputs all of the system names in all caps.

When importing this list as a CSV route the plugin does not recognize my having arrived in the next system. As a result I have to manually cycle the pluign to the next system. 

Even in game system names are displayed as all caps.

It would be very useful to me for this plugin to ignore case when comparing arrival systems to imported CSV route files. 

I suspect this would be simple to implement, and I can see no downsides to this choice. 

Thank you for the wonderful tool.

**Comment by CMDR-Kiel42** [comment]
Indeed, that was [a quick fix](https://github.com/CMDR-Kiel42/EDMC_SpanshRouter/commit/167d1b0b14f61c522b84fc84539d140f22dd05b6). Thanks for the heads up and the positive feedback :)
